### ISSUE TITLE
2.0 is out

### ISSUE THREAD

**Issue by SiriosDev** [n3rd4i/scrcpy#14]

**Comment by p-schneider** [comment]
The updated Version is now available: https://community.chocolatey.org/packages/scrcpy/2.0

**Comment by p-schneider** [comment]
But both the 1.25 and 2.0 version don't currently install because the dist zip files from https://github.com/Genymobile/scrcpy/releases/ now use a subfolder within the zip file.
The install script would have to be adjusted.
A [fix/workaround is available](https://github.com/n3rd4i/scrcpy/pull/10/commits/734f29b9e1f91928e00931737aed4302b129978c) in #10.
